##
# OS
#
# @file
# @version 0.1
CC=gcc
CFLAGS=-pthread -Wall
DESP=main.c

main: $(DESP)
	@echo "=====================start complier======================="
	$(CC) -o $@ $^ $(CFLAGS)
	@echo "=====================complier finish======================"

clean:
	rm main
# end
